### ISSUE TITLE
MG and MIS ready for review: Sam 

### ISSUE THREAD

**Issue by DeeshaPatel** [DeeshaPatel/CAS-741-Solar-Cooker#30]
Hello @samm82, 

Thanks for your help. My [MG](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/ec4598b0fbc843af8be4b3bce90434fcd0c4cd72/docs/Design/SoftArchitecture/MG.pdf) and [MIS](https://github.com/DeeshaPatel/CAS-741-Solar-Cooker/blob/ec4598b0fbc843af8be4b3bce90434fcd0c4cd72/docs/Design/SoftDetailedDes/MIS.pdf) are ready to review. I am open to your suggestions. :)

**Comment by samm82** [comment]
Since #37 is a non-trivial issue that will affect a lot of your modules (and I think I've given you quite a lot to do!) I think I'm going to stop my review here. Great document! It was quite clear what the intent between each module/function was.

Feel free to close this issue for now! (I'm not a contributor yet, so I can't do it myself lol.) I might take a second pass later to see if I missed anything, but based on my workload, this is unlikely. 😅

**Comment by DeeshaPatel** [comment]
Thank you so much @samm82 for your valuable feedback. :)
